export const rankingList: string[] = [
  "POGAČAR Tadej",
  "VINGEGAARD Jonas",
  "DEL TORO Isaac",
  "EVENEPOEL Remco",
  "SEIXAS Paul",
  "PHILIPSEN Jasper",
  "VAN DER POEL Mathieu",
  "LIPOWITZ Florian",
  "SCHMID Mauro",
  "PIDCOCK Tom",
  "GRÉGOIRE Romain",
  "SKJELMOSE Mattias",
  "ARENSMAN Thymen",
  "MCNULTY Brandon",
  "MARTINEZ Lenny",
  "GODON Dorian",
  "MERLIER Tim",
  "HEALY Ben",
  "PEDERSEN Mads",
  "JORGENSON Matteo",
  "RICCITELLO Matthew",
  "JOHANNESSEN Tobias Halland",
  "HINDLEY Jai",
  "AYUSO Juan",
  "IZAGIRRE Ion",
  "BERNAL Egan",
  "DE LIE Arnaud",
  "STORER Michael",
  "VAUQUELIN Kévin",
  "UIJTDEBROEKS Cian",
  "YATES Adam",
  "GIRMAY Biniam",
  "BITTNER Pavel",
  "PLAPP Luke",
  "ARANBURU Alex",
  "WÆRENSKJOLD Søren",
  "TIBERI Antonio",
  "STUYVEN Jasper",
  "KUSS Sepp",
  "BAUDIN Alex",
  "O'CONNOR Ben",
  "KOOIJ Olav",
  "PIGANZOLI Davide",
  "TEJADA Harold",
  "TRENTIN Matteo",
  "JEGAT Jordan",
  "GANNA Filippo",
  "ABRAHAMSEN Jonas",
  "DELETTRE Alexandre",
  "ALAPHILIPPE Julian",
  "KANTER Max",
  "CARAPAZ Richard",
  "WRIGHT Fred",
  "HIGUITA Sergio",
  "HERMANS Quinten",
  "VAN WILDER Ilan",
  "VERMEERSCH Florian",
  "SIMMONS Quinn",
  "WELLENS Tim",
  "GEE-WEST Derek",
  "PARET-PEINTRE Valentin",
  "BERCKMOES Jenno",
  "HIRSCHI Marc",
  "TURGIS Anthony",
  "SKUJIŅŠ Toms",
  "VINOKUROV Nicolas",
  "VOISARD Yannis",
  "BERWICK Sebastian",
  "BALLERINI Davide",
  "COSTIOU Ewen",
  "TEUNISSEN Mike",
  "VACEK Mathias",
  "MATTHEWS Michael",
  "ASKEY Lewis",
  "ARMIRAIL Bruno",
  "FRETIN Milan",
  "GROßSCHARTNER Felix",
  "MARTIN Guillaume",
  "VALGREN Michael",
  "CHARMIG Anthon",
  "VELASCO Simone",
  "PRODHOMME Nicolas",
  "FRIGO Marco",
  "TRÆEN Torstein",
  "PARET-PEINTRE Aurélien",
  "HAGENES Per Strand",
  "MOHORIČ Matej",
  "GARCÍA PIERNA Raúl",
  "ENGELHARDT Felix",
  "CARUSO Damiano",
  "VAN DIJKE Tim",
  "ZIMMERMANN Georg",
  "DELBOVE Joris",
  "HARPER Chris",
  "ROMO Javier",
  "JOHANNESSEN Anders Halland",
  "STEINHAUSER Georg",
  "VAN GILS Maxim",
  "POLITT Nils",
  "VERSTRYNGE Emiel",
  "BIESTERBOS Frits",
  "MEURISSE Xandro",
  "BENOOT Tiesj",
  "ACKERMANN Pascal",
  "BIERMANS Jenthe",
  "PLUIMERS Rick",
  "CASTRILLO Pablo",
  "THOMAS Benjamin",
  "CEPEDA Jefferson Alveiro",
  "GAVIRIA Fernando",
  "CAMPENAERTS Victor",
  "VAN DEN BROEK Frank",
  "FOSS Tobias",
  "BAUHAUS Phil",
  "MOLENAAR Alex",
  "DE KLEIJN Arvid",
  "BRAZ AFONSO Clément",
  "PARRA José Félix",
  "SLOCK Liam",
  "VERCHER Mattéo",
  "VAN MOER Brent",
  "VAN EETVELT Lennert",
  "DEBRUYNE Ramses",
  "GATE Aaron",
  "RUBIO Einer",
  "TARLING Joshua",
  "BERTHET Clément",
  "BREUILLARD Nicolas",
  "BALDERSTONE Abel",
  "CORT Magnus",
  "HOOLE Daan",
  "EENKHOORN Pascal",
  "NEILANDS Krists",
  "KWIATKOWSKI Michał",
  "BENNETT George",
  "BOL Cees",
  "OLDANI Stefano",
  "DENZ Nico",
  "HALLER Marco",
  "ARTZ Huub",
  "NICOLAU Joel",
  "VERONA Carlos",
  "RUSSO Clément",
  "VAN BAARLE Dylan",
  "LE BERRE Mathis",
  "CRAPS Lars",
  "BARGUIL Warren",
  "AFFINI Edoardo",
  "PAGE Hugo",
  "LOUVEL Matis",
  "VERVAEKE Louis",
  "PLANCKAERT Edward",
  "VAN ASBROECK Tom",
  "CATTANEO Mattia",
  "GERMANI Lorenzo",
  "ASGREEN Kasper",
  "OLIVEIRA Nelson",
  "PACHER Quentin",
  "VEISTROFFER Baptiste",
  "STEWART Jake",
  "STANNARD Robert",
  "RICKAERT Jonas",
  "SKAARSETH Anders",
  "VAN MECHELEN Vlad",
  "GUERNALEC Thibault",
  "O'BRIEN Kelland",
  "DEGENKOLB John",
  "QUINN Sean",
  "DILLIER Silvan",
  "MÄRKL Niklas",
  "HESSMANN Michel",
  "HOWSON Damien",
  "GRADEK Kamil",
  "TRATNIK Jan",
  "VAN DEN BERG Julius",
  "OTRUBA Jakub",
  "AZPARREN Xabier Mikel",
  "DURBRIDGE Luke",
  "WALKER Max",
  "VAN LERBERGHE Bert",
  "DHONDT Robbe",
  "MARSMAN Tim",
  "KIRSCH Alex",
  "ALLEGAERT Piet",
]
