export const rankingList: Record<string, number> = {
  "VINGEGAARD Jonas": 1,
  "DE LIE Arnaud": 2,
  "ANDRESEN Tobias Lund": 3,
  "SCARONI Christian": 4,
  "MAGNIER Paul": 5,
  "PELLIZZARI Giulio": 6,
  "GALL Felix": 7,
  "VINE Jay": 8,
  "CHRISTEN Jan": 9,
  "GROENEWEGEN Dylan": 10,
  "BERNAL Egan": 11,
  "STRONG Corbin": 12,
  "YATES Adam": 13,
  "MILAN Jonathan": 14,
  "CICCONE Giulio": 15,
  "STORER Michael": 16,
  "ARENSMAN Thymen": 17,
  "KUBIŠ Lukáš": 18,
  "O'CONNOR Ben": 19,
  "NARVÁEZ Jhonatan": 20,
  "SILVA Guillermo Thomas": 21,
  "RONDEL Mathys": 22,
  "GANNA Filippo": 23,
  "ZANA Filippo": 24,
  "MORGADO António": 25,
  "STUYVEN Jasper": 26,
  "VERNON Ethan": 27,
  "BUITRAGO Santiago": 28,
  "VENDRAME Andrea": 29,
  "AULAR Orluis": 30,
  "MALUCELLI Matteo": 31,
  "HINDLEY Jai": 32,
  "ULISSI Diego": 33,
  "KUSS Sepp": 34,
  "TURNER Ben": 35,
  "ZAMBANINI Edoardo": 36,
  "MOZZATO Luca": 37,
  "PIGANZOLI Davide": 38,
  "GROVES Kaden": 39,
  "GEE-WEST Derek": 40,
  "MENTEN Milan": 41,
  "KULSET Johannes": 42,
  "PENHOËT Paul": 43,
  "LEKNESSUND Andreas": 44,
  "SOLER Marc": 45,
  "ARRIETA Igor": 46,
  "LONARDI Giovanni": 47,
  "SEGAERT Alec": 48,
  "BETTIOL Alberto": 49,
  "CHRISTEN Fabio": 50,
  "CARUSO Damiano": 51,
  "VLASOV Aleksandr": 52,
  "SOBRERO Matteo": 53,
  "BALLERINI Davide": 54,
  "ACKERMANN Pascal": 55,
  "LÓPEZ Harold Martín": 56,
  "ENGELHARDT Felix": 57,
  "LARSEN Niklas": 58,
  "RUBIO Einer": 59,
  "KOPECKÝ Matyáš": 60,
  "MOSCHETTI Matteo": 61,
  "CRESCIOLI Ludovico": 62,
  "PINARELLO Alessandro": 63,
  "RACCAGNI NOVIERO Andrea": 64,
  "DVERSNES LAVIK Fredrik": 65,
  "EULÁLIO Afonso": 66,
  "BLIKRA Erlend": 67,
  "ROMO Javier": 68,
  "HARPER Chris": 69,
  "SHEFFIELD Magnus": 70,
  "GAROFOLI Gianmarco": 71,
  "SVESTAD-BÅRDSENG Embret": 72,
  "HUENS Axel": 73,
  "STORK Florian": 74,
  "MILESI Lorenzo": 75,
  "LØLAND Sakarias Koller": 76,
  "TEUTENBERG Tim Torn": 77,
  "PESENTI Thomas": 78,
  "VALGREN Michael": 79,
  "CAMPENAERTS Victor": 80,
  "ZANONCELLO Enrico": 81,
  "DENZ Nico": 82,
  "VAN DEN BROEK Frank": 83,
  "MÜHLBERGER Gregor": 84,
  "ALBANESE Vincenzo": 85,
  "MAS Enric": 86,
  "GUALDI Simone": 87,
  "DONALDSON Robert": 88,
  "HATHERLY Alan": 89,
  "GARCÍA CORTINA Iván": 90,
  "HOLTER Ådne": 91,
  "HOELGAARD Markus": 92,
  "VAN UDEN Casper": 93,
  "BUSATTO Francesco": 94,
  "STEWART Jake": 95,
  "DONOVAN Mark": 96,
  "VAN DIJKE Mick": 97,
  "ALEOTTI Giovanni": 98,
  "KIELICH Timo": 99,
  "BELOKI Markel": 100,
  "LEMMEN Bart": 101,
  "MARCELLUSI Martin": 102,
  "TJØTTA Martin": 103,
  "VAN EETVELT Lennert": 104,
  "PLANCKAERT Edward": 105,
  "PLOWRIGHT Jensen": 106,
  "MAGLI Filippo": 107,
  "NAESEN Oliver": 108,
  "KELDERMAN Wilco": 109,
  "ROLLAND Brieuc": 110,
  "MIHKELS Madis": 111,
  "CAVAGNA Rémi": 112,
  "BARTA Will": 113,
  "MAESTRI Mirco": 114,
  "ZWIEHOFF Ben": 115,
  "HAMILTON Chris": 116,
  "AERTS Toon": 117,
  "GUDMESTAD Tord": 118,
  "BARGUIL Warren": 119,
  "TSVETKOV Nikita": 120,
  "ROCHAS Rémy": 121,
  "DE LA CRUZ David": 122,
  "WALSCHEID Max": 123,
  "SEVILLA Diego Pablo": 124,
  "GONZÁLEZ David": 125,
  "PEDERSEN Rasmus Søjberg": 126,
  "PALETTI Luca": 127,
  "TURCONI Filippo": 128,
  "GHEBREIGZABHIER Amanuel": 129,
  "SHAW James": 130,
  "ZUKOWSKY Nickolas": 131,
  "WARBASSE Larry": 132,
  "BJERG Mikkel": 133,
  "STAUNE-MITTET Johannes": 134,
  "REINDERS Elmar": 135,
  "JACOBS Johan": 136,
  "GEENS Jonas": 137,
  "POELS Wout": 138,
  "MOSCON Gianni": 139,
  "VAN DER LEE Jardi Christiaan": 140,
  "ROTA Lorenzo": 141,
  "RUTSCH Jonas": 142,
  "SCOTSON Callum": 143,
  "OLIVEIRA Nelson": 144,
  "LIVYNS Arjen": 145,
  "VAN DEN BOSSCHE Fabio": 146,
  "SLOCK Liam": 147,
  "LEEMREIZE Gijs": 148,
  "JUUL-JENSEN Christopher": 149,
  "DE VRIES Hartthijs": 150,
  "VAN GESTEL Dries": 151,
  "MIHOLJEVIĆ Fran": 152,
  "SWIFT Connor": 153,
  "VERGALLITO Luca": 154,
  "STANNARD Robert": 155,
  "HAIG Jack": 156,
  "LÓPEZ Juan Pedro": 157,
  "SCHULTZ Nick": 158,
  "BARTHE Cyril": 159,
  "FLYNN Sean": 160,
  "BAIS Mattia": 161,
  "KENCH Josh": 162,
  "DE JONG Timo": 163,
  "MIFSUD Andrea": 164,
  "NABERMAN Tim": 165,
  "FROIDEVAUX Robin": 166,
  "RAFFERTY Darren": 167,
  "SMITH Dion": 168,
  "MULLEN Ryan": 169,
  "ROJAS Vicente": 170,
  "BAYER Tobias": 171,
  "CONSONNI Simone": 172,
  "KOPECKÝ Tomáš": 173,
  "PAASSCHENS Mathijs": 174,
  "REX Tim": 175,
  "TONELLI Alessandro": 176,
  "LIENHARD Fabian": 177,
  "TAROZZI Manuele": 178,
  "BATTISTELLA Samuele": 179,
  "HIRT Jan": 180,
  "BASTIAENS Ayco": 181,
  "BAX Sjoerd": 182,
  "BOUWMAN Koen": 183,
  "PRICE-PEJTERSEN Johan": 184,
};
